version: "3.8"
services:
  aggregator:
    build:
      context: $MONOREPO_DIR
      dockerfile: docker/samples/cpp/aggregator.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
        - "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:main"
    image: "${SAMPLES_CPP_AGGREGATOR_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - $MONOREPO_DIR/src/samples/cpp/aggregator:/home/docker/ament_ws/src/aggregator
  producer:
    build:
      context: $MONOREPO_DIR
      dockerfile: docker/samples/cpp/producer.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
        - "${SAMPLES_CPP_PRODUCER_IMAGE:?}:main"
    image: "${SAMPLES_CPP_PRODUCER_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - $MONOREPO_DIR/src/samples/cpp/producer:/home/docker/ament_ws/src/producer
  transformer:
    build:
      context: $MONOREPO_DIR
      dockerfile: docker/samples/cpp/transformer.Dockerfile
      cache_from:
        - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
        - "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:main"
    image: "${SAMPLES_CPP_TRANSFORMER_IMAGE:?}:${TAG}"
    user: ${FIXUID:?}:${FIXGID:?}
    volumes:
      - $MONOREPO_DIR/src/samples/cpp/transformer:/home/docker/ament_ws/src/transformer
