---
camera_object_detection_node:
  ros__parameters:
    front_center_camera_topic: /CAM_FRONT/image_rect_compressed
    front_right_camera_topic: /CAM_FRONT_RIGHT/image_rect_compressed
    front_left_camera_topic: /CAM_FRONT_LEFT/image_rect_compressed
    publish_vis_topic: false
    publish_obstacle_topic: /obstacles
    model_path: /perception_models/yolov8m.pt
    onnx_model_path: /perception_models/yolov8m.onnx
    tensorRT_model_path: /perception_models/yolov8m.engine
    image_size: 640
    nuscenes: true
    compressed: true
