right_traffic_signs_node:
  ros__parameters:
    camera_topic: /camera/left/image_color
    publish_vis_topic: /traffic_signs_viz
    publish_detection_topic: /traffic_signs/left
    model_path: /perception_models/traffic_signs.pt
    crop_mode: CenterCrop
    image_size: 1024
    save_detections: false

center_traffic_signs_node:
  ros__parameters:
    camera_topic: /camera/center/image_color
    publish_vis_topic: /traffic_signs_viz
    publish_detection_topic: /traffic_signs/center
    model_path: /perception_models/traffic_signs.pt
    crop_mode: CenterCrop
    image_size: 1024
    save_detections: false

right_traffic_signs_node:
  ros__parameters:
    camera_topic: /camera/right/image_color
    publish_vis_topic: /traffic_signs_viz
    publish_detection_topic: /traffic_signs/right
    model_path: /perception_models/traffic_signs.pt
    crop_mode: CenterCrop
    image_size: 1024
    save_detections: false
