---
lane_detection_node:
  ros__parameters:
    camera_topic: /camera/left/image_color
    publish_vis_topic: /camera/left/lanes_viz
    publish_lanes_topic: /camera/left/lanes
    save_images: false
    save_images_path: /tmp
    publish_source_image: false
    debug_node: false
