---
lane_detection_node:
  ros__parameters:
    camera_topic: /CAM_FRONT/image_rect_compressed
    publish_vis_topic: /CAM_FRONT/lanes_viz
    publish_lanes_topic: /CAM_FRONT/lanes
    save_images: false
    save_images_path: /tmp
    publish_source_image: false
    debug_node: false
