image_width: 1280
image_height: 1024
camera_name: camera_pano_ww
camera_matrix:
  rows: 3
  cols: 3
  data: [1920.0, 0.0, 640.0,
         0.0, 1920.0, 512.0,
         0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.1, 0.05, -0.001, -0.001, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [1920.0, 0.0, 640.0, 0.0,
         0.0, 1920.0, 512.0, 0.0,
         0.0, 0.0, 1.0, 0.0]
