---
# TODO(wato): change the parameters value
hd_map_service:
  ros__parameters:
    version: 1
    osm_map_filename: "Town10HD.osm"
    visualization_output_topic: "hd_map_viz"
    route_output_topic: "hd_route_map"
    start_output_topic: "hd_map_start_lanelet"
    end_output_topic: "hd_map_end_lanelet"
    desired_lane_output: "hd_map_desired_lane"
    current_lane_output_topic: "hd_map_current_lane"
    traffic_light_input_topic: "traffic_light"
    traffic_sign_input_topic: "/traffic_signs"
    pedestrian_input_topic: "pedestrian"
    point_input_topic: "clicked_point"
    query_point_input_topic: "query_point"
