version: "3.8"
services:
  camera_detection:
    build:
      context: ..
      dockerfile: docker/camera_detection/camera_detection.Dockerfile
      cache_from:
        - camera_detection:latest
    image: camera_detection
    user: ${FIXUID:?}:${FIXGID:?}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]