version: "3.8"

services:
  foxglove:
    extends:
      file: ../docker-compose.infrastructure.yaml
      service: foxglove
  
  data_stream:
    extends:
      file: ../docker-compose.infrastructure.yaml
      service: data_stream