image_width: 1280
image_height: 1024
camera_name: camera_pano_nw
camera_matrix:
  rows: 3
  cols: 3
  data: [1042.302602, 0.000000, 632.116724,
         0.000000, 1043.358501, 558.181329,
         0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.092733, 0.093596, 0.000610, 0.000079, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [1020.622986, 0.000000, 631.960497, 0.000000,
         0.000000, 1024.017944, 559.203525, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
