image_width: 1280
image_height: 1024
camera_name: camera_pano_ss
camera_matrix:
  rows: 3
  cols: 3
  data: [958.680575, 0.000000, 661.771302,
         0.000000, 964.678782, 601.788498,
         0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.119615, 0.042847, 0.011411, 0.003261, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [912.418884, 0.000000, 668.153131, 0.000000,
         0.000000, 921.557983, 616.931485, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
