image_width: 1280
image_height: 1024
camera_name: camera_pano_se
camera_matrix:
  rows: 3
  cols: 3
  data: [1050.020010, 0.000000, 630.027523,
         0.000000, 1051.936100, 535.347907,
         0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.086566, 0.087426, 0.001555, 0.000679, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [1029.500122, 0.000000, 630.650143, 0.000000,
         0.000000, 1033.889893, 536.565122, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
