image_width: 1280
image_height: 1024
camera_name: camera_pano_ee
camera_matrix:
  rows: 3
  cols: 3
  data: [1023.174272, 0.000000, 610.920696,
         0.000000, 1023.863472, 534.535890,
         0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.121900, 0.146239, 0.009346, -0.006408, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [1011.306519, 0.000000, 603.042686, 0.000000,
         0.000000, 1009.264282, 543.632782, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
