---
image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1043.44857, 0., 636.766006,
         0., 1043.927225, 547.328589,
         0., 0., 1.]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.088314, 0.079344, 0.002677, 0.001808, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1020.002014, 0., 638.796232, 0.,
         0., 1024.373779, 549.809626, 0.,
         0., 0., 1., 0.]
