image_width: 1280
image_height: 1024
camera_name: camera_pano_se
camera_matrix:
  rows: 3
  cols: 3
  data: [1012.838584, 0.000000, 582.993121,
         0.000000, 1014.182114, 549.263388,
         0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.077957, 0.041881, 0.007075, -0.008824, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [983.331421, 0.000000, 568.594622, 0.000000,
         0.000000, 994.549255, 555.859802, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
