---
image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1047.871102, 0., 594.417519,
         0., 1048.798729, 535.298492,
         0., 0., 1.]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.085847, 0.092966, 0.002749, -0.000924, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1031.266602, 0., 593.59561, 0.,
         0., 1030.913452, 537.415754, 0.,
         0., 0., 1., 0.]
