image_width: 1280
image_height: 1024
camera_name: camera_pano_sw
camera_matrix:
  rows: 3
  cols: 3
  data: [1045.836914, 0.000000, 596.843087,
         0.000000, 1045.801603, 550.543861,
         0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.081469, 0.082938, 0.000697, -0.003486, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [1025.804565, 0.000000, 592.290170, 0.000000,
         0.000000, 1029.770630, 551.010299, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
