image_width: 1280
image_height: 1024
camera_name: camera_pano_ss
camera_matrix:
  rows: 3
  cols: 3
  data: [1051.907507, 0.000000, 638.425923,
         0.000000, 1051.700231, 519.096473,
         0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.098593, 0.113964, -0.000239, -0.001034, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [1033.785767, 0.000000, 636.528584, 0.000000,
         0.000000, 1034.025024, 518.174104, 0.000000,
         0.000000, 0.000000, 1.000000, 0.000000]
